name: unit-test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - ""
          - --release
        toolchain:
          - stable
          - beta
          - nightly
        features:
          - ""
          - --no-default-features
          - --features futures-core
          - --no-default-features --features futures-core
        include:
          - toolchain: nightly
            features: --features nightly-async-iterator
          - toolchain: nightly
            features: --features nightly-extend-one
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose ${{ matrix.config }} ${{ matrix.features }}
      - run: cargo test --verbose ${{ matrix.config }} ${{ matrix.features }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo clippy
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --verbose
